version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env-postgres
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: postgres