version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:13
    restart: always
    ports:
      - "3005:5432"
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgresql.conf:/postgresql.conf
    command: postgres -c config_file=/postgresql.conf

volumes:
  postgres:
    name: postgres