apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
  labels:
    app: postgres
    name: postgres-configmap
data:
  DATABASE_URL: postgresql://node_api:node_api_password@localhost:3005/node_api
  POSTGRES_DB: node_api
  POSTGRES_PASSWORD: node_api_password
  POSTGRES_USER: node_api
